apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /app-service
        backend:
          serviceName: app-service
          servicePort: 80
