apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-edit
  namespace: dev # grants permissions within the "dev" namespace
subjects:
- kind: Group
  name: dev-group # permissions for the group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit # read/write access
  apiGroup: rbac.authorization.k8s.io
