
baseURL = "https://freight-trust.github.io/infrastructure"
disablePathToLower = true
languageCode = "en-us"
title = "InfraFreight"
theme = "docter"

[params]
  # the name of your project and a link back to the home page
  home = "InfraFreight"
  # A small snippet of text above the sidebar:
  # subtitle = ""

  author = "org name"
  author_url= "https://github.com/freight-trust"

  # Point readers to your repo and invite them to edit pages 
  repo_host = "Github"
  repo = "https://githug.com/freight-trust/infrastructure/"

  # Add a reference to a logo, which will appear in the top right
  # logourl = ""
  # logoalt = ""

  # Mention your hosting provider 
  hosted_on = "hosting provider"
  hosted_on_url= "#"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

  # brand color
  # brand_color = "#7300ac"